# Generated by Django 4.1.5 on 2023-02-21 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departameento',
            new_name='Departamento',
        ),
    ]
