# Generated by Django 4.1.5 on 2023-02-22 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0004_alter_departamento_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('name', 'short_name')},
        ),
    ]
